# Generated by Django 5.2 on 2025-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referee",
            name="tournaments",
            field=models.ManyToManyField(
                blank=True, related_name="referees", to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="tennisplayer",
            name="tournaments",
            field=models.ManyToManyField(to="tournaments.tournament"),
        ),
    ]
