# Generated by Django 5.2 on 2025-04-08 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="end_Date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="tournament",
            old_name="start_Date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="tournament",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_participants",
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("REGISTRATION", "Registration Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                ],
                default="UPCOMING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
