# Generated by Django 5.2 on 2025-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_rename_end_date_tournament_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_ELIMINATION", "Single Elimination"),
                    ("ROUND_ROBIN", "Round Robin"),
                ],
                default="SINGLE_ELIMINATION",
                help_text="Format of the tournament",
                max_length=20,
            ),
        ),
    ]
