# Generated by Django 5.2 on 2025-05-12 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_tournament_tournament_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="pending_registrations",
            field=models.ManyToManyField(
                blank=True,
                related_name="pending_tournament_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
