# Generated by Django 5.2 on 2025-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="requires_action",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TOURNAMENT", "Tournament"),
                    ("MATCH", "Match"),
                    ("REGISTRATION_APPROVAL", "Registration Approval"),
                    ("SYSTEM", "System"),
                ],
                max_length=30,
            ),
        ),
    ]
